### ISSUE TITLE
Package is invalid: 'CRX_HEADER_INVALID'.

### ISSUE THREAD

**Issue by badjuice** [catppuccin/opera-gx#4]
Getting this when trying to drag and drop a theme from the `/themes` directory into the `opera://mods` tab.

![image](https://github.com/catppuccin/opera-gx/assets/25462821/af3a6bd7-5b57-486a-8ad8-6a8e89459018)

My browser info:
```
Opera GX
LVL5 (core: 109.0.5097.108)
Checking for updates…
Update stream:Early Access
System:Windows 11 64-bit
Chromium version:123.0.6312.124
```

**Comment by uncenter** [comment]
Do the files before https://github.com/catppuccin/opera-gx/commit/66cb4057837073e6d913053cf6d8fe0c4adde6d0 work?

**Comment by fdaumas** [comment]
yes the files before https://github.com/catppuccin/opera-gx/commit/66cb4057837073e6d913053cf6d8fe0c4adde6d0 work fine

**Comment by uncenter** [comment]
Gotcha. Usually browser extensions work with just zip files but I guess Opera mandates the CRX header. @isabelroses do you know how you zipped the CRX files before my Whiskers PR?

**Comment by isabelroses** [comment]
> Gotcha. Usually browser extensions work with just zip files but I guess Opera mandates the CRX header. @isabelroses do you know how you zipped the CRX files before my Whiskers PR?

For my rough memory, i signed them all myself by zipping each of them up in the browser.

**Comment by uncenter** [comment]
Ah, shoot. I'm not sure if we can automate this. Feel free to revert my previous PR for now!

**Comment by isabelroses** [comment]
Reverted for now, https://github.com/catppuccin/opera-gx/pull/5. Creating a meta issue to track automation.
